apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: "anonymous"
  deployment:
    accessible_namespaces: ["m", "istio-system"]
    view_only_mode: false
  server:
    web_root: "/kiali"