---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver # Перезаписываем уже существующий ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://auth-service.m.svc.cluster.local/api/v1/auth/validate
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  rules:
    - http:
        paths:
          - path: / # Направляем все запросы к echoserver
            pathType: Prefix
            backend:
              service:
                name: echoserver
                port:
                  number: 80