apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task04-servicemonitor
  labels:
    app: task04
    release: prometheus
spec:
  selector:
    matchLabels:
      app: task04
  endpoints:
    - port: web
      path: /actuator/prometheus
      interval: 15s