server:
  port: 8000
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:myDb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
  datasource:
    url: jdbc:postgresql://psql-postgresql:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: user_pg
    password: pass_pg
springdoc:
  api-docs:
    path: /api-docs