server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:myDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password