apiVersion: apps/v1
kind: Deployment
metadata:
  name: task03-deployment
  labels:
    app: task03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task03
  template:
    metadata:
      labels:
        app: task03
    spec:
      containers:
        - name: task03
          image: dbelokursky/task03:0.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
